//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class Агенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Агенты()
        {
            this.Заявки = new HashSet<Заявки>();
            this.ИсторИзменПриорит = new HashSet<ИсторИзменПриорит>();
        }
    
        public int id { get; set; }
        public string Компания { get; set; }
        public string Тип { get; set; }
        public string ЮридичАдрес { get; set; }
        public Nullable<long> ИНН { get; set; }
        public string КПП { get; set; }
        public string ФИОДиректора { get; set; }
        public string КонтактДанные { get; set; }
        public byte[] Логотип { get; set; }
        public string Приоритет { get; set; }
        public string ТочкиПродаж { get; set; }
        public string РеализацияПродукции { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявки> Заявки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ИсторИзменПриорит> ИсторИзменПриорит { get; set; }
    }
}
