//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public int id { get; set; }
        public int id_агента { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public Nullable<int> id_продуктов { get; set; }
        public Nullable<decimal> Общая_стоимость { get; set; }
        public string Состояние { get; set; }
    
        public virtual Агенты Агенты { get; set; }
        public virtual Продукция Продукция { get; set; }
    }
}
