//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ИсторияИзмКолМатер
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> id_материала { get; set; }
        public Nullable<int> НовоеКол { get; set; }
    
        public virtual Материалы Материалы { get; set; }
        public string СписокМатериалов => Материалы.Наименование;
    }
}
