//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИсторИзменПриорит
    {
        public int id { get; set; }
        public Nullable<int> id_агента { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> НоваяПриорит { get; set; }
    
        public virtual Агенты Агенты { get; set; }
    }
}
