//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class Материалы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Материалы()
        {
            this.ИсторияИзмКолМатер = new HashSet<ИсторияИзмКолМатер>();
            this.Поставщики = new HashSet<Поставщики>();
        }
    
        public int id { get; set; }
        public string Наименование { get; set; }
        public string Тип { get; set; }
        public byte[] Изображение { get; set; }
        public Nullable<int> Цена { get; set; }
        public Nullable<int> КолНаСкладе { get; set; }
        public Nullable<int> МинКол { get; set; }
        public Nullable<int> КолвУпаковке { get; set; }
        public string ЕдинИзмер { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ИсторияИзмКолМатер> ИсторияИзмКолМатер { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Поставщики> Поставщики { get; set; }
    }
}
