//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class Производство
    {
        public int id { get; set; }
        public Nullable<System.TimeSpan> Время { get; set; }
        public Nullable<decimal> Себестоимость { get; set; }
        public Nullable<int> НомерЦеха { get; set; }
        public Nullable<int> НеобхКолЧел { get; set; }
    }
}
