//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.ВремяРаботыСотрудн = new HashSet<ВремяРаботыСотрудн>();
            this.ПередвижСотрудников = new HashSet<ПередвижСотрудников>();
        }
    
        public int id { get; set; }
        public string ФИО { get; set; }
        public Nullable<System.DateTime> ДатаРожд { get; set; }
        public string ПаспортДанные { get; set; }
        public string БанковсРеквизиты { get; set; }
        public string Семья { get; set; }
        public string ПроблСоЗдоровьем { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ВремяРаботыСотрудн> ВремяРаботыСотрудн { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПередвижСотрудников> ПередвижСотрудников { get; set; }
    }
}
